
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.build.dart"
    - "**/*.build.dart.dart"
    - "build/**"
    - "**/*.gr.dart"
    - "**/*.pb.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbserver.dart"
    - "**/*.pbgrpc.dart"
    - "**/*.pbmap.dart"
    - "**/*.shim.dart"
    - "**/*.config.dart"
    - "**/*.theme.dart"
    - "**/*.l10n.dart"
    - "**/*.auto_route.dart"
    - "test_results/**"
    - "**/*_test.dart"

linter:
  rules:
    # Flutter recommended rules
    - prefer_const_constructors
    - prefer_final_locals
    - avoid_print
    - always_use_package_imports
    - public_member_api_docs
    - avoid_empty_else
    - cascade_invocations
    - no_leading_underscores_for_local_identifiers
    - sort_child_properties_last
    - use_colored_box
    - use_decorated_box
    - use_super_parameters
    - avoid_unnecessary_containers
    - avoid_redundant_argument_values
    - avoid_types_as_parameter_names
    - no_logic_in_create_state
    - no_duplicate_case_values
    - prefer_single_quotes
    - unnecessary_lambdas
    - use_if_null_to_convert_nulls_to_bools
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - avoid_returning_null_for_void
    - avoid_types_on_closure_parameters
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_function_declarations_over_variables
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - test_types_in_equals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_to_and_as_if_applicable

  # Additional rules for code quality
    - sort_constructors_first
    - avoid_catches_without_on_clauses
    - avoid_classes_with_only_static_members
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - file_names
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - recursive_getters
    - slash_for_doc_comments
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_parenthesis
    - unrelated_type_equality_checks
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - valid_regexps

   